### PR TITLE
Added implementation for database to retrieve entityand sort by attribute

### LINKED ISSUE #115: 💡 [REQUEST] - <Database entries are not in displayed in any particular order>
### Start Date

_No response_

### Implementation PR

_No response_

### Reference Issues

_No response_

### Summary

Currently, the list being displayed from the database in terms of food items are in a random order or are being displayed in order of when they were added. 

### Basic Example

Carrots being higher up in the list order than avocado

Want to ensure that it is alphabetical ordering 

### Drawbacks

_No response_

### Unresolved questions

_No response_

### PR DESCRIPTION
**Pull request by ktha423**
Closes issue #115
Created a method in database manager class for retrieving entities from database based on ordering by attributes. Currently, orders in ascending order but can easily be changed in future through some minimal code to accommodate for descending order as well.

### CODE REVIEW

**Review by mmcc944 — CHANGES_REQUESTED** [review]
Food items now appear in alphabetical order but when you use the search functionality they do not return in alphabetical order

image

**Comment by ochu761** [comment]
> Food items now appear in alphabetical order but when you use the search functionality they do not return in alphabetical order

Good spotting with your check! Potential fix could be to manually sort the list alphabetically (using a built-in sort method for collections?) at line 106 in the SearchPopUpController.java (just before the return in searchList())

**Review by ochu761 — CHANGES_REQUESTED** [review]
> Food items now appear in alphabetical order but when you use the search functionality they do not return in alphabetical order

Good spotting with your check! Potential fix could be to manually sort the list alphabetically (using a built-in sort method for collections?) at line 106 in the SearchPopUpController.java (just before the return in searchList())

**Review by mmcc944 — CHANGES_REQUESTED** [review]
You added the getTableSorted method twice to the DatabaseManager. Just need to remove that and everything is working fine.

**Review by ochu761 — APPROVED** [review]
Duplicate getTableSorted method resolved. Sorting works as expected, good work!

**Pull request merged**
