### PR TITLE
Improved navigation quality across application

### LINKED ISSUE #76: 💡 [REQUEST] - Add navigation across application
### Start Date

27/09/22

### Implementation PR

#80

### Summary

Add buttons to allow the user to navigate between all appropriate scenes in the application. 

- [X] Back button from the search menu
- [X] Rename buttons to be more descriptive 

### Basic Example

Not required

### Drawbacks

New buttons will need to be worked into the resize responsive version of the application that is being worked on at present

### PR DESCRIPTION
**Pull request by samanthamebius**
Removed some dead ends in the project by adding buttons and renamed some buttons to be more meaningful. Closes #76

### CODE REVIEW

**Review by mmcc944 — DISMISSED** [review]
Everything functioning properly. Remember to remove the button once the proper functionality to do this is completed.

**Review by mmcc944 — CHANGES_REQUESTED** [review]
Everything functioning properly but the branch should be merged into the release 1.0 branch rather than the main.

**Comment by samanthamebius** [comment]
> Everything functioning properly but the branch should be merged into the release 1.0 branch rather than the main.

Good spotting! I have fixed that now!

**Review by mmcc944 — APPROVED** [review]
Nicely done

**Pull request merged**
